#!/bin/sh
# Vendors the mistlib source tree into vendor/mistlib from the repository
# configured via the MISTLIB_REPO / MISTLIB_REF environment variables
# (falling back to .env for whichever of those is not already set in the
# environment), so that people without access to the private mistlib
# repository can still build this project. Run this (and commit the
# resulting diff) whenever mistlib should be updated.
# POSIX-sh counterpart of vendor-mistlib.ps1 for Linux/macOS.
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
env_file="$root/.env"

env_repo=${MISTLIB_REPO:-}
env_ref=${MISTLIB_REF:-}

repo=""
ref=""
if [ -f "$env_file" ]; then
    while IFS= read -r line || [ -n "$line" ]; do
        line=$(printf '%s' "$line" | tr -d '\r')
        case $line in
            MISTLIB_REPO=*) repo=${line#MISTLIB_REPO=} ;;
            MISTLIB_REF=*) ref=${line#MISTLIB_REF=} ;;
        esac
    done < "$env_file"
fi

# Environment variables take priority; .env only fills in what's not already set.
[ -n "$env_repo" ] && repo=$env_repo
[ -n "$env_ref" ] && ref=$env_ref

if [ -z "$repo" ]; then
    echo "vendor-mistlib: MISTLIB_REPO is not set (set the env var or add it to .env)" >&2
    exit 1
fi
[ -n "$ref" ] || ref=develop

vendor_dir="$root/vendor"
target="$vendor_dir/mistlib"
tmp="$vendor_dir/.mistlib.tmp"
mkdir -p "$vendor_dir"
rm -rf "$tmp"

echo "vendor-mistlib: fetching $repo @ $ref"
if printf '%s' "$ref" | grep -Eq '^[0-9a-fA-F]{40}$'; then
    # Full commit hash: shallow-fetch that exact revision.
    git init -q "$tmp"
    git -C "$tmp" remote add origin "$repo"
    git -C "$tmp" fetch -q --depth 1 origin "$ref"
    git -C "$tmp" checkout -q FETCH_HEAD
else
    git clone -q --depth 1 --branch "$ref" "$repo" "$tmp"
fi

sha=$(git -C "$tmp" rev-parse HEAD)

# Assemble a minimal tree: only what this project actually consumes.
stage="$vendor_dir/.mistlib.stage"
rm -rf "$stage"
mkdir -p "$stage"
cp -R "$tmp/mistlib-core" "$stage/mistlib-core"
cp -R "$tmp/mistlib-native" "$stage/mistlib-native"
cp "$tmp/LICENSE" "$stage/LICENSE"

# Prune tests/examples/benches: this is vendored for public consumption and
# only needs to build, not test; mistlib-native's out-of-line test modules
# are all declared behind #[cfg(test)], so removing them cannot break
# `cargo build`.
prune_crate() {
    crate_dir=$1
    for d in tests examples benches; do
        [ -d "$crate_dir/$d" ] && rm -rf "$crate_dir/$d"
    done
    src_dir="$crate_dir/src"
    if [ -d "$src_dir" ]; then
        find "$src_dir" -type d -name tests -prune -exec rm -rf {} +
        find "$src_dir" -type f -name 'tests.rs' -delete
    fi
    # Drop [[example]]/[[test]]/[[bench]] target declarations left dangling
    # by the removals above (e.g. upstream's [[example]] name = "sim_run"),
    # since cargo fails target resolution if the referenced path is gone.
    cargo_toml="$crate_dir/Cargo.toml"
    if [ -f "$cargo_toml" ]; then
        awk '
            /^\[\[(example|test|bench)\]\]$/ { skip=1; next }
            /^\[/ { skip=0 }
            skip { next }
            { print }
        ' "$cargo_toml" > "$cargo_toml.tmp"
        mv "$cargo_toml.tmp" "$cargo_toml"
    fi
}
prune_crate "$stage/mistlib-core"
prune_crate "$stage/mistlib-native"

# Minimal workspace manifest: upstream's root Cargo.toml lists members
# (e.g. mistlib-wasm) that are not vendored here.
cat > "$stage/Cargo.toml" <<'EOF'
# Generated by scripts/vendor-mistlib -- do not edit; minimal workspace for the vendored members.
[workspace]
members = [
    "mistlib-core",
    "mistlib-native",
]
resolver = "2"
EOF

{
    echo "repo: <configured by MISTLIB_REPO>"
    echo "ref: $ref"
    echo "commit: $sha"
    echo "vendored-at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "contents: mistlib-core, mistlib-native (tests, examples, and benches pruned), LICENSE"
} > "$stage/VENDORED_FROM"

rm -rf "$tmp"
# Replace the target's contents rather than the directory itself: editors and
# language servers often hold a handle on vendor/mistlib, which makes removing
# the directory fail on Windows ("Device or resource busy").
mkdir -p "$target"
find "$target" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
find "$stage" -mindepth 1 -maxdepth 1 -exec mv {} "$target"/ \;
rmdir "$stage"
echo "vendor-mistlib: vendored $ref ($sha) into vendor/mistlib"
echo "vendor-mistlib: review the diff and commit it."
