#!/bin/sh
# Vendors the mistlib source tree into vendor/mistlib from the repository
# configured in .env (MISTLIB_REPO / MISTLIB_REF), so that people without
# access to the private mistlib repository can still build this project.
# Run this (and commit the resulting diff) whenever mistlib should be updated.
# POSIX-sh counterpart of vendor-mistlib.ps1 for Linux/macOS.
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
env_file="$root/.env"
if [ ! -f "$env_file" ]; then
    echo "vendor-mistlib: .env not found (copy .env.example and set MISTLIB_REPO)" >&2
    exit 1
fi

repo=""
ref=""
while IFS= read -r line || [ -n "$line" ]; do
    line=$(printf '%s' "$line" | tr -d '\r')
    case $line in
        MISTLIB_REPO=*) repo=${line#MISTLIB_REPO=} ;;
        MISTLIB_REF=*) ref=${line#MISTLIB_REF=} ;;
    esac
done < "$env_file"

if [ -z "$repo" ]; then
    echo "vendor-mistlib: MISTLIB_REPO is not set in .env" >&2
    exit 1
fi
[ -n "$ref" ] || ref=develop

vendor_dir="$root/vendor"
target="$vendor_dir/mistlib"
tmp="$vendor_dir/.mistlib.tmp"
mkdir -p "$vendor_dir"
rm -rf "$tmp"

echo "vendor-mistlib: fetching $repo @ $ref"
if printf '%s' "$ref" | grep -Eq '^[0-9a-fA-F]{40}$'; then
    # Full commit hash: shallow-fetch that exact revision.
    git init -q "$tmp"
    git -C "$tmp" remote add origin "$repo"
    git -C "$tmp" fetch -q --depth 1 origin "$ref"
    git -C "$tmp" checkout -q FETCH_HEAD
else
    git clone -q --depth 1 --branch "$ref" "$repo" "$tmp"
fi

sha=$(git -C "$tmp" rev-parse HEAD)

# Assemble a minimal tree: only what this project actually consumes.
stage="$vendor_dir/.mistlib.stage"
rm -rf "$stage"
mkdir -p "$stage"
cp -R "$tmp/mistlib-core" "$stage/mistlib-core"
cp -R "$tmp/mistlib-native" "$stage/mistlib-native"
cp "$tmp/LICENSE" "$stage/LICENSE"

# Minimal workspace manifest: upstream's root Cargo.toml lists members
# (e.g. mistlib-wasm) that are not vendored here.
cat > "$stage/Cargo.toml" <<'EOF'
# Generated by scripts/vendor-mistlib — do not edit; minimal workspace for the vendored members.
[workspace]
members = [
    "mistlib-core",
    "mistlib-native",
]
resolver = "2"
EOF

{
    echo "repo: <configured by MISTLIB_REPO>"
    echo "ref: $ref"
    echo "commit: $sha"
    echo "vendored-at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "contents: mistlib-core, mistlib-native, LICENSE"
} > "$stage/VENDORED_FROM"

rm -rf "$tmp"
rm -rf "$target"
mv "$stage" "$target"
echo "vendor-mistlib: vendored $ref ($sha) into vendor/mistlib"
echo "vendor-mistlib: review the diff and commit it."
