# Vendors the mistlib source tree into vendor/mistlib from the repository
# configured via the MISTLIB_REPO / MISTLIB_REF environment variables (falling
# back to .env for whichever of those is not already set in the environment),
# so that people without access to the private mistlib repository can still
# build this project. Run this (and commit the resulting diff) whenever
# mistlib should be updated.
$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $root '.env'

$vars = @{}
if (Test-Path $envFile) {
    foreach ($line in Get-Content $envFile) {
        $line = $line.Trim()
        if ($line -eq '' -or $line.StartsWith('#')) { continue }
        $idx = $line.IndexOf('=')
        if ($idx -lt 1) { continue }
        $vars[$line.Substring(0, $idx).Trim()] = $line.Substring($idx + 1).Trim()
    }
}

# Environment variables take priority; .env only fills in what's not already set.
$repo = $env:MISTLIB_REPO
if (-not $repo) { $repo = $vars['MISTLIB_REPO'] }
$ref = $env:MISTLIB_REF
if (-not $ref) { $ref = $vars['MISTLIB_REF'] }
if (-not $repo) { throw 'vendor-mistlib: MISTLIB_REPO is not set (set the env var or add it to .env)' }
if (-not $ref) { $ref = 'develop' }

$vendorDir = Join-Path $root 'vendor'
$target = Join-Path $vendorDir 'mistlib'
$tmp = Join-Path $vendorDir '.mistlib.tmp'
New-Item -ItemType Directory -Force $vendorDir | Out-Null
if (Test-Path $tmp) { Remove-Item -Recurse -Force $tmp }

Write-Host "vendor-mistlib: fetching $repo @ $ref"
if ($ref -match '^[0-9a-fA-F]{40}$') {
    # Full commit hash: shallow-fetch that exact revision.
    git init -q $tmp
    git -C $tmp remote add origin $repo
    git -C $tmp fetch -q --depth 1 origin $ref
    git -C $tmp checkout -q FETCH_HEAD
} else {
    git clone -q --depth 1 --branch $ref $repo $tmp
}
if ($LASTEXITCODE -ne 0) { throw "vendor-mistlib: git fetch of $repo @ $ref failed" }

$sha = (git -C $tmp rev-parse HEAD).Trim()

# Assemble a minimal tree: only what this project actually consumes.
$stage = Join-Path $vendorDir '.mistlib.stage'
if (Test-Path $stage) { Remove-Item -Recurse -Force $stage }
New-Item -ItemType Directory -Force $stage | Out-Null
Copy-Item -Recurse (Join-Path $tmp 'mistlib-core') (Join-Path $stage 'mistlib-core')
Copy-Item -Recurse (Join-Path $tmp 'mistlib-native') (Join-Path $stage 'mistlib-native')
Copy-Item (Join-Path $tmp 'LICENSE') $stage

# Prune tests/examples/benches: this is vendored for public consumption and
# only needs to build, not test; mistlib-native's out-of-line test modules
# are all declared behind #[cfg(test)], so removing them cannot break
# `cargo build`.
foreach ($crate in @('mistlib-core', 'mistlib-native')) {
    $crateDir = Join-Path $stage $crate
    foreach ($dir in @('tests', 'examples', 'benches')) {
        $p = Join-Path $crateDir $dir
        if (Test-Path $p) { Remove-Item -Recurse -Force $p }
    }
    $srcDir = Join-Path $crateDir 'src'
    if (Test-Path $srcDir) {
        $testDirs = @(Get-ChildItem -Path $srcDir -Recurse -Directory -Filter 'tests')
        foreach ($d in $testDirs) {
            if (Test-Path $d.FullName) { Remove-Item -Recurse -Force $d.FullName }
        }
        $testFiles = @(Get-ChildItem -Path $srcDir -Recurse -File -Filter 'tests.rs')
        foreach ($f in $testFiles) {
            if (Test-Path $f.FullName) { Remove-Item -Force $f.FullName }
        }
    }
    # Drop [[example]]/[[test]]/[[bench]] target declarations left dangling
    # by the removals above (e.g. upstream's [[example]] name = "sim_run"),
    # since cargo fails target resolution if the referenced path is gone.
    $cargoToml = Join-Path $crateDir 'Cargo.toml'
    if (Test-Path $cargoToml) {
        $linesIn = [System.IO.File]::ReadAllLines($cargoToml)
        $linesOut = New-Object System.Collections.Generic.List[string]
        $skip = $false
        foreach ($line in $linesIn) {
            if ($line -match '^\[\[(example|test|bench)\]\]$') { $skip = $true; continue }
            if ($line -match '^\[') { $skip = $false }
            if ($skip) { continue }
            $linesOut.Add($line)
        }
        $text = if ($linesOut.Count -gt 0) { ($linesOut -join "`n") + "`n" } else { '' }
        [System.IO.File]::WriteAllText($cargoToml, $text, (New-Object System.Text.UTF8Encoding($false)))
    }
}

# Minimal workspace manifest: upstream's root Cargo.toml lists members
# (e.g. mistlib-wasm) that are not vendored here.
@'
# Generated by scripts/vendor-mistlib -- do not edit; minimal workspace for the vendored members.
[workspace]
members = [
    "mistlib-core",
    "mistlib-native",
]
resolver = "2"
'@ | Set-Content -Encoding ascii (Join-Path $stage 'Cargo.toml')

@(
    "repo: <configured by MISTLIB_REPO>"
    "ref: $ref"
    "commit: $sha"
    "vendored-at: $((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'))"
    "contents: mistlib-core, mistlib-native (tests, examples, and benches pruned), LICENSE"
) | Set-Content -Encoding ascii (Join-Path $stage 'VENDORED_FROM')

Remove-Item -Recurse -Force $tmp
# Replace the target's contents rather than the directory itself: editors and
# language servers often hold a handle on vendor/mistlib, which makes removing
# the directory fail on Windows ("Device or resource busy").
New-Item -ItemType Directory -Force $target | Out-Null
Get-ChildItem -Force $target | Remove-Item -Recurse -Force
Get-ChildItem -Force $stage | Move-Item -Destination $target
Remove-Item $stage
Write-Host "vendor-mistlib: vendored $ref ($sha) into vendor/mistlib"
Write-Host 'vendor-mistlib: review the diff and commit it.'
