# Vendors the mistlib source tree into vendor/mistlib from the repository
# configured in .env (MISTLIB_REPO / MISTLIB_REF), so that people without
# access to the private mistlib repository can still build this project.
# Run this (and commit the resulting diff) whenever mistlib should be updated.
$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $root '.env'
if (-not (Test-Path $envFile)) { throw 'vendor-mistlib: .env not found (copy .env.example and set MISTLIB_REPO)' }

$vars = @{}
foreach ($line in Get-Content $envFile) {
    $line = $line.Trim()
    if ($line -eq '' -or $line.StartsWith('#')) { continue }
    $idx = $line.IndexOf('=')
    if ($idx -lt 1) { continue }
    $vars[$line.Substring(0, $idx).Trim()] = $line.Substring($idx + 1).Trim()
}

$repo = $vars['MISTLIB_REPO']
$ref = $vars['MISTLIB_REF']
if (-not $repo) { throw 'vendor-mistlib: MISTLIB_REPO is not set in .env' }
if (-not $ref) { $ref = 'develop' }

$vendorDir = Join-Path $root 'vendor'
$target = Join-Path $vendorDir 'mistlib'
$tmp = Join-Path $vendorDir '.mistlib.tmp'
New-Item -ItemType Directory -Force $vendorDir | Out-Null
if (Test-Path $tmp) { Remove-Item -Recurse -Force $tmp }

Write-Host "vendor-mistlib: fetching $repo @ $ref"
if ($ref -match '^[0-9a-fA-F]{40}$') {
    # Full commit hash: shallow-fetch that exact revision.
    git init -q $tmp
    git -C $tmp remote add origin $repo
    git -C $tmp fetch -q --depth 1 origin $ref
    git -C $tmp checkout -q FETCH_HEAD
} else {
    git clone -q --depth 1 --branch $ref $repo $tmp
}
if ($LASTEXITCODE -ne 0) { throw "vendor-mistlib: git fetch of $repo @ $ref failed" }

$sha = (git -C $tmp rev-parse HEAD).Trim()

# Assemble a minimal tree: only what this project actually consumes.
$stage = Join-Path $vendorDir '.mistlib.stage'
if (Test-Path $stage) { Remove-Item -Recurse -Force $stage }
New-Item -ItemType Directory -Force $stage | Out-Null
Copy-Item -Recurse (Join-Path $tmp 'mistlib-core') (Join-Path $stage 'mistlib-core')
Copy-Item -Recurse (Join-Path $tmp 'mistlib-native') (Join-Path $stage 'mistlib-native')
Copy-Item (Join-Path $tmp 'LICENSE') $stage

# Minimal workspace manifest: upstream's root Cargo.toml lists members
# (e.g. mistlib-wasm) that are not vendored here.
@'
# Generated by scripts/vendor-mistlib — do not edit; minimal workspace for the vendored members.
[workspace]
members = [
    "mistlib-core",
    "mistlib-native",
]
resolver = "2"
'@ | Set-Content -Encoding ascii (Join-Path $stage 'Cargo.toml')

@(
    "repo: <configured by MISTLIB_REPO>"
    "ref: $ref"
    "commit: $sha"
    "vendored-at: $((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'))"
    "contents: mistlib-core, mistlib-native, LICENSE"
) | Set-Content -Encoding ascii (Join-Path $stage 'VENDORED_FROM')

Remove-Item -Recurse -Force $tmp
if (Test-Path $target) { Remove-Item -Recurse -Force $target }
Move-Item $stage $target
Write-Host "vendor-mistlib: vendored $ref ($sha) into vendor/mistlib"
Write-Host 'vendor-mistlib: review the diff and commit it.'
